# Generated by Django 4.2.7 on 2023-11-30 14:30

import admin_theme.tools
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eshop.models
import eshop.validators
import main_config.tools
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_theme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='سفارش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='توضیحات')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop.category')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='درصد تخفیف')),
                ('code', models.CharField(default=admin_theme.tools.create_code, max_length=255, unique=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('uuid', models.CharField(default=eshop.models.create_factor_id, max_length=20, verbose_name='factor_id')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='مالیات')),
                ('value_added_tax', models.PositiveBigIntegerField(default=0, verbose_name='مالیات بر ارزش افزوده')),
                ('discount_code', models.CharField(default='', max_length=50, verbose_name='کد تخفیف')),
                ('discount_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('total_weight', models.PositiveIntegerField(default=0, verbose_name='وزن کل محصولات')),
                ('payment_tracking_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='کد رهگیری پرداخت')),
                ('payment_id', models.PositiveBigIntegerField(default=eshop.models.get_random_payment_id, verbose_name='شماره پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع')),
                ('sales_reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='sales reference ID')),
                ('res_code', models.BigIntegerField(blank=True, null=True, verbose_name='res code =')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('shipping_tracking_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='کد رهگیری ارسال')),
                ('name_family', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('state', models.CharField(max_length=255, verbose_name='استان')),
                ('city', models.CharField(max_length=255, verbose_name='شهر')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('post_code', models.CharField(max_length=255, verbose_name='کد پستی')),
                ('customer_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'paymwent method',
                'verbose_name_plural': 'روش های پرداخت',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='کد')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'وضعیت پرداخت',
                'verbose_name_plural': 'وضعیت های پرداخت',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=main_config.tools.UploadToPathAndRename('products'), verbose_name='تصویر محصول')),
                ('image_cropping_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='cropping info')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='توضیحات')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='release date')),
                ('weight', models.PositiveIntegerField(default=0, help_text='input value as Grams', verbose_name='وزن')),
                ('count', models.PositiveIntegerField(default=100, verbose_name='تعداد')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('min_purchase', models.PositiveIntegerField(default=0, verbose_name='minimum purchase')),
                ('max_purchase', models.PositiveIntegerField(default=100, verbose_name='maximum purchase')),
                ('has_tax', models.BooleanField(default=False, verbose_name='مالیات اضافه شود')),
                ('tax_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
                ('has_value_added_tax', models.BooleanField(default=False, verbose_name='افزودن مالیات بر ارزش افزوده')),
                ('meta_keywords', models.CharField(blank=True, help_text="separate with comma (used in the site's header for seo)", max_length=200, null=True, verbose_name='کلمات کلیدی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('site_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سایت')),
                ('site_icon', models.ImageField(upload_to=main_config.tools.UploadToPathAndRename('setting'), verbose_name='آیکون سایت (favicon)')),
                ('site_logo', models.ImageField(upload_to=main_config.tools.UploadToPathAndRename('setting'), verbose_name='لوگوی سایت')),
                ('contact_us', ckeditor.fields.RichTextField()),
                ('product_finishing_alert', models.PositiveIntegerField(default=10, verbose_name='حداقل تعداد هشدار اتمام محصول')),
                ('value_added_tax_percent', models.PositiveIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='درصد مالیات بر ارزش افزوده')),
                ('has_value_added_tax', models.BooleanField(default=True, verbose_name='افزودن مالیات بر ارزش افزوده')),
                ('soomasoft_webservice_user', models.CharField(default='', max_length=50, verbose_name='نام کاربری وب سرویس سوماسافت')),
                ('soomasoft_webservice_password', models.CharField(default='', max_length=50, verbose_name='رمز عبور وب سرویس سوماسافت')),
                ('soomasoft_webservice_otp_number', models.CharField(default='', max_length=50, verbose_name='کد otp سوماسافت')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='کد')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'وضعیت ارسال',
                'verbose_name_plural': 'وضعیت های ارسال',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SmsVerificcationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sms_verification_uuid', models.CharField(default=eshop.models.create_uuid, max_length=40, verbose_name='Mobile verification uuid')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile')),
                ('activation_code', models.PositiveBigIntegerField(verbose_name='کد فعالسازی')),
            ],
            options={
                'verbose_name': 'SMS verification code',
                'verbose_name_plural': 'SMS verification codes',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('payment_methods', models.ManyToManyField(to='eshop.paymentmethod', verbose_name='روش های پرداخت')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش های ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('from_weight', models.PositiveIntegerField(default=0, help_text='گرم', verbose_name='از وزن')),
                ('to_weight', models.PositiveIntegerField(default=0, help_text='گرم', verbose_name='تا وزن')),
                ('price', models.PositiveIntegerField(default=0, help_text='toman', verbose_name='قیمت')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='توضیحات')),
                ('states', models.ManyToManyField(to='admin_theme.state', verbose_name='استان های مقصد')),
            ],
            options={
                'verbose_name': 'هزینه ارسال',
                'verbose_name_plural': 'هزینه های ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آدرس')),
                ('receiver', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی گیرنده')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تماس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postcode', models.CharField(max_length=10, validators=[eshop.validators.validate_postcode], verbose_name='کد پستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_theme.state', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس ارسال',
                'verbose_name_plural': 'آدرس های ارسال',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(default='', max_length=255, verbose_name='عنوان')),
                ('value', models.CharField(default='', max_length=255, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductMonetaryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='آپشن')),
                ('price', models.PositiveIntegerField(default=0, help_text='Toman', verbose_name='قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی پولی محصول',
                'verbose_name_plural': 'ویژگی های پولی محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main_config.tools.UploadToPathAndRename('products'), verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_methods',
            field=models.ManyToManyField(to='eshop.shippingmethod', verbose_name='shipping merthods'),
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('product', models.CharField(max_length=255, verbose_name='محصول')),
                ('monetary_option', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویژگی پولی محصول')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم های فاکتور',
            },
        ),
        migrations.AddField(
            model_name='factor',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.paymentmethod', verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='factor',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.paymentstatus', verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='factor',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='factor',
            name='shipping_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingstatus', verbose_name='وضعیت ارسال'),
        ),
        migrations.AddField(
            model_name='factor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='درصد تخفیف')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.cart', verbose_name='سبد خرید')),
                ('monetary_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.productmonetaryoption', verbose_name='ویژگی پولی محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم های سبد خرید',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'category'), ('title', 'brand')},
        ),
    ]
